<?php

namespace Symfony\Lsp\Tools\Dogfood;

/**
 * Renders the support ledger as a self-contained HTML page with a score
 * trend chart and a latest-state table. No external assets, so the page
 * works offline from the Gérard workspace.
 */
final class SupportHtmlReport
{
    /** @param list<array<array-key, mixed>> $entries */
    public function render(array $entries): string
    {
        $data = json_encode($entries, \JSON_UNESCAPED_SLASHES | \JSON_HEX_TAG | \JSON_THROW_ON_ERROR);

        return str_replace('__DATA__', $data, self::TEMPLATE);
    }

    private const TEMPLATE = <<<'HTML'
        <!DOCTYPE html>
        <html lang="en">
        <head>
        <meta charset="utf-8">
        <title>Symfony LSP dogfood support</title>
        <style>
        body { font: 14px/1.5 system-ui, sans-serif; margin: 2rem auto; max-width: 70rem; color: #1a1a2e; padding: 0 1rem; }
        h1 { font-size: 1.4rem; }
        h2 { font-size: 1.1rem; margin-top: 2rem; }
        svg { width: 100%; height: auto; background: #fafafa; border: 1px solid #e2e2e2; border-radius: 6px; }
        table { border-collapse: collapse; width: 100%; }
        th, td { text-align: left; padding: .35rem .6rem; border-bottom: 1px solid #e2e2e2; }
        th { background: #f4f4f8; }
        td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
        .up { color: #0a7d33; }
        .down { color: #b3261e; }
        .legend { display: flex; flex-wrap: wrap; gap: .3rem 1rem; margin: .6rem 0; font-size: .85rem; }
        .legend span { display: inline-flex; align-items: center; gap: .35rem; cursor: pointer; }
        .legend i { width: 1rem; height: 3px; display: inline-block; }
        .muted { color: #777; }
        details { margin: .15rem 0; }
        .gap { font-size: .85rem; color: #555; }
        </style>
        </head>
        <body>
        <h1>Symfony LSP dogfood support</h1>
        <p class="muted">Fraction of expected request kinds (completion, hover, definition, references)
        answered per probe, averaged per category and project. Generated by <code>tools/dogfood-support --record</code>.</p>
        <h2>Trend</h2>
        <div id="legend" class="legend"></div>
        <svg id="chart" viewBox="0 0 1000 420" role="img" aria-label="Support score trend"></svg>
        <h2>Latest per project</h2>
        <table>
        <thead><tr><th>Project</th><th class="num">Support</th><th class="num">&Delta;</th><th class="num">Probes</th><th>Run</th><th>Gaps (&lt;100%)</th></tr></thead>
        <tbody id="latest"></tbody>
        </table>
        <script>
        const DATA = __DATA__;
        const runs = [...new Set(DATA.map(e => e.run))].sort();
        const projects = [...new Set(DATA.map(e => e.project))].sort();
        const byProject = Object.fromEntries(projects.map(p => [p, DATA.filter(e => e.project === p).sort((a, b) => a.run < b.run ? -1 : 1)]));
        const palette = ['#2563eb', '#dc2626', '#059669', '#d97706', '#7c3aed', '#0891b2', '#be185d', '#4d7c0f', '#b45309', '#1e40af', '#9333ea', '#0f766e', '#a21caf', '#374151', '#ca8a04', '#065f46'];
        const color = p => palette[projects.indexOf(p) % palette.length];
        const hidden = new Set();

        const X0 = 55, X1 = 985, Y0 = 15, Y1 = 385;
        const x = run => runs.length < 2 ? (X0 + X1) / 2 : X0 + (X1 - X0) * runs.indexOf(run) / (runs.length - 1);
        const y = score => Y1 - (Y1 - Y0) * score;

        function overallSeries() {
            return runs.map(run => {
                const scores = DATA.filter(e => e.run === run).map(e => e.score);
                return { run, score: scores.reduce((a, b) => a + b, 0) / scores.length, count: scores.length };
            });
        }

        function draw() {
            const svg = document.getElementById('chart');
            let parts = [];
            for (let pct = 0; pct <= 100; pct += 25) {
                const yy = y(pct / 100);
                parts.push(`<line x1="${X0}" y1="${yy}" x2="${X1}" y2="${yy}" stroke="#e2e2e2"/>`);
                parts.push(`<text x="${X0 - 8}" y="${yy + 4}" text-anchor="end" font-size="11" fill="#777">${pct}%</text>`);
            }
            const step = Math.max(1, Math.ceil(runs.length / 8));
            runs.forEach((run, i) => {
                if (i % step === 0 || i === runs.length - 1) {
                    parts.push(`<text x="${x(run)}" y="${Y1 + 16}" text-anchor="middle" font-size="10" fill="#777">${run}</text>`);
                }
            });
            const series = [...projects.filter(p => !hidden.has(p)).map(p => ({ name: p, points: byProject[p], width: 1.5, dash: '' }))];
            if (!hidden.has('overall')) {
                series.push({ name: 'overall', points: overallSeries().map(e => ({ ...e, project: 'overall' })), width: 3, dash: '' });
            }
            for (const s of series) {
                const stroke = s.name === 'overall' ? '#111' : color(s.name);
                const path = s.points.map(e => `${x(e.run).toFixed(1)},${y(e.score).toFixed(1)}`).join(' ');
                parts.push(`<polyline points="${path}" fill="none" stroke="${stroke}" stroke-width="${s.width}"/>`);
                for (const e of s.points) {
                    const label = `${s.name} ${e.run}: ${(100 * e.score).toFixed(1)}%`;
                    parts.push(`<circle cx="${x(e.run).toFixed(1)}" cy="${y(e.score).toFixed(1)}" r="3.2" fill="${stroke}"><title>${label}</title></circle>`);
                }
            }
            svg.innerHTML = parts.join('');
        }

        function legend() {
            const container = document.getElementById('legend');
            container.innerHTML = '';
            for (const name of ['overall', ...projects]) {
                const item = document.createElement('span');
                const stroke = name === 'overall' ? '#111' : color(name);
                item.innerHTML = `<i style="background:${stroke}"></i>${name}`;
                item.style.opacity = hidden.has(name) ? .35 : 1;
                item.onclick = () => { hidden.has(name) ? hidden.delete(name) : hidden.add(name); legend(); draw(); };
                container.appendChild(item);
            }
        }

        function latestTable() {
            const body = document.getElementById('latest');
            for (const project of projects) {
                const history = byProject[project];
                const last = history[history.length - 1];
                const previous = history.length > 1 ? history[history.length - 2] : null;
                const delta = previous ? 100 * (last.score - previous.score) : null;
                const gaps = Object.entries(last.categories || {}).filter(([, s]) => s < 1).sort((a, b) => a[1] - b[1]);
                const gapHtml = gaps.length
                    ? `<details><summary class="gap">${gaps.length} categories</summary>${gaps.map(([c, s]) => `<div class="gap">${c}: ${(100 * s).toFixed(0)}%</div>`).join('')}</details>`
                    : '<span class="gap">none</span>';
                const row = document.createElement('tr');
                row.innerHTML = `<td>${project}</td>`
                    + `<td class="num">${(100 * last.score).toFixed(1)}%</td>`
                    + `<td class="num ${delta > 0 ? 'up' : delta < 0 ? 'down' : ''}">${delta === null ? '—' : (delta > 0 ? '+' : '') + delta.toFixed(1)}</td>`
                    + `<td class="num">${last.probeCount}</td>`
                    + `<td class="muted">${last.run}${previous && previous.fingerprint !== last.fingerprint ? ' *' : ''}</td>`
                    + `<td>${gapHtml}</td>`;
                body.appendChild(row);
            }
        }

        legend();
        draw();
        latestTable();
        </script>
        </body>
        </html>
        HTML;
}
