#!/usr/bin/env bash
set -euo pipefail

directory=${BASH_SOURCE[0]%/*}
if [[ "$directory" == "${BASH_SOURCE[0]}" ]]; then directory=.; fi
cd "$directory"

cargo=$(rustup which cargo)
toolchain_bin=${cargo%/*}
export PATH="$toolchain_bin:$PATH"

"$cargo" fmt --check
"$cargo" test --locked
"$cargo" check --locked --target wasm32-wasip2
